## 분석용 기초
### NumPy 계속

In [2]:
# numpY fhem
import numpy as np

In [3]:
#python 리스트를 생성 -> 넘파이 배열로 변경
a=[1,3,5,7,9]
na=np.array(a)

In [4]:
a

[1, 3, 5, 7, 9]

In [5]:
print(a)

[1, 3, 5, 7, 9]

In [6]:
na

array([1, 3, 5, 7, 9])

In [7]:
print(na)

[1 3 5 7 9]

In [10]:
nb=np.array([
    [1,2,3],
    [4,5,6]
])#2행 3열 2차원배열

In [12]:
# 2차원 배열 nb의 1행을 추출
nb[1]

array([4, 5, 6])

In [11]:
nb[1,2] #nb배열의 1행의 2열을 가지고와라

np.int64(6)

- Python의 기본형 NumPy에서 np.int64랑 동일

In [ ]:
nc = np.array ([1.2,2.3,3.4])
nc[1]

In [13]:
nb.sum() # 행령 모든 요소를 합한다

np.int64(21)

In [14]:
nb.sum(axis=0) #열기준으로 합산

array([5, 7, 9])

In [15]:
nb.sum(axis=1) #행 기준으로 합산

array([ 6, 15])

In [19]:
#랜덤 데이터 생성
np.random.rand(5)

array([0.18185263, 0.69246247, 0.08587439, 0.34403226, 0.91823601])

In [23]:
np.random.randint(1,10,5)

array([5, 2, 7, 8, 7], dtype=int32)

In [ ]:
# 정규화
nd =np.array([10,20,30])

normalized =(nd-nd.mean())/nd.std()

normalized

array([-1.22474487,  0.        ,  1.22474487])

In [27]:
scores =np.array([50,80,90,60,30])
scores[scores>=60]

array([80, 90, 60])

In [28]:
scores.mean()

np.float64(62.0)

In [ ]:
-정리
    -List: 파이선 for문 사용
    NumPy: c언어 기반처리

### pandas

-엑셀을 코드로 다루는 도구
-표형태의 데이터를 처리할 수 있음
-데이터분석시 가장 많이 사용되는 라이브러리
#### 설치

```bash
```

In [29]:
!pip install pandas

Collecting pandas
  Downloading pandas-3.0.1-cp312-cp312-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy>=1.26.0 in c:\sourcebank\iot-python-2026\iot-venv\lib\site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\sourcebank\iot-python-2026\iot-venv\lib\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Downloading tzdata-2025.3-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in c:\sourcebank\iot-python-2026\iot-venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.1-cp312-cp312-win_amd64.whl (9.7 MB)
   ---------------------------------------- 0.0/9.7 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.7 MB ? eta -:--:--
   -- ------------------------------------- 0.5/9.7 MB 1.1 MB/s eta 0:00:09
   -- ------------------------------------- 0.5/9.7 MB 1.1 MB/s eta 0:00:09
   --- ------------------------------------ 0.8/9.7 MB 799.2 kB/s eta 0:00:12
   --- ------------------------------------ 0.8/9.7 MB 799.2 kB/s eta 0:00:12
   --- ------------------------------------ 0.8/9.7 MB 799.2 kB/s eta 0:00:12
   --- ------------------------------------ 0.8/9.7 MB 799.2 kB/s eta 0:00:12
   ---- ----------------------------------- 1.0/9.7 MB 606.3 kB/s eta 0:00:15
   ---- ----------------------------------- 1.0/9.7 MB 606.3 kB/s eta 0:00:15
   ---- ----------------------------------- 1.0/9.7 MB 606.3 kB/s eta 0:00:15
   ---- ----------------------------------- 1.0/9.7 MB 606.3 kB/s eta 0:00:15
   ---- ----------------------------------- 1.0/9.7 MB 606.3 kB/s eta 0:00:15
   ---- ----------------------------------- 1.0/9.7 MB 606.3 kB/s eta 0:00:15
   ----- ---------------------------------- 1.3/9.7 MB 411.7 kB/s eta 0:00:21
   ----- ---------------------------------- 1.3/9.7 MB 411.7 kB/s eta 0:00:21
   ----- ---------------------------------- 1.3/9.7 MB 411.7 kB/s eta 0:00:21
   ----- ---------------------------------- 1.3/9.7 MB 411.7 kB/s eta 0:00:21
   ----- ---------------------------------- 1.3/9.7 MB 411.7 kB/s eta 0:00:21
   ----- ---------------------------------- 1.3/9.7 MB 411.7 kB/s eta 0:00:21
   ----- ---------------------------------- 1.3/9.7 MB 411.7 kB/s eta 0:00:21
   ------ --------------------------------- 1.6/9.7 MB 323.9 kB/s eta 0:00:26
   ------ --------------------------------- 1.6/9.7 MB 323.9 kB/s eta 0:00:26
   ------ --------------------------------- 1.6/9.7 MB 323.9 kB/s eta 0:00:26
   ------ --------------------------------- 1.6/9.7 MB 323.9 kB/s eta 0:00:26
   ------- -------------------------------- 1.8/9.7 MB 325.8 kB/s eta 0:00:25
   ------- -------------------------------- 1.8/9.7 MB 325.8 kB/s eta 0:00:25
   -------- ------------------------------- 2.1/9.7 MB 346.4 kB/s eta 0:00:23
   -------- ------------------------------- 2.1/9.7 MB 346.4 kB/s eta 0:00:23
   -------- ------------------------------- 2.1/9.7 MB 346.4 kB/s eta 0:00:23
   --------- ------------------------------ 2.4/9.7 MB 357.0 kB/s eta 0:00:21
   --------- ------------------------------ 2.4/9.7 MB 357.0 kB/s eta 0:00:21
   --------- ------------------------------ 2.4/9.7 MB 357.0 kB/s eta 0:00:21
   --------- ------------------------------ 2.4/9.7 MB 357.0 kB/s eta 0:00:21
   --------- ------------------------------ 2.4/9.7 MB 357.0 kB/s eta 0:00:21
   ---------- ----------------------------- 2.6/9.7 MB 340.1 kB/s eta 0:00:21
   ---------- ----------------------------- 2.6/9.7 MB 340.1 kB/s eta 0:00:21
   ---------- ----------------------------- 2.6/9.7 MB 340.1 kB/s eta 0:00:21
   ----------- ---------------------------- 2.9/9.7 MB 351.7 kB/s eta 0:00:20
   ------------ --------------------------- 3.1/9.7 MB 371.4 kB/s eta 0:00:18
   ------------- -------------------------- 3.4/9.7 MB 393.2 kB/s eta 0:00:17
   --------------- ------------------------ 3.7/9.7 MB 415.4 kB/s eta 0:00:15
   --------------- ------------------------ 3.7/9.7 MB 415.4 kB/s eta 0:00:15
   ---------------- ----------------------- 3.9/9.7 MB 426.3 kB/s eta 0:00:14
   ----------------- ---------------------- 4.2/9.7 MB 445.4 kB/s eta 0:00:13
   ----------------- ---------------------- 4.2/9.7 MB 445.4 kB/s eta 0:00:13
   ------------------ --------------------- 4.5/9.7 MB 461.2 kB/s eta 0:00:12
   ------------------- -------------------- 4.7/9.7 MB 479.3 kB/s eta 0:00:11
   ------------------- -------------------- 4.7/9.7 MB 479.3 kB/s eta 0:00:11
   -------------------- ------------------- 5.0/9.7 MB 486.3 kB/s eta 0:00:10
   -------------------- ------------------- 5.0/9.7 MB 486.3 kB/s eta 0:00:10
   -------------------- ------------------- 5.0/9.7 MB 486.3 kB/s eta 0:00:10
   --------------------- ------------------ 5.2/9.7 MB 481.5 kB/s eta 0:00:10
   --------------------- ------------------ 5.2/9.7 MB 481.5 kB/s eta 0:00:10
   --------------------- ------------------ 5.2/9.7 MB 481.5 kB/s eta 0:00:10
   ---------------------- ----------------- 5.5/9.7 MB 474.6 kB/s eta 0:00:09
   ---------------------- ----------------- 5.5/9.7 MB 474.6 kB/s eta 0:00:09
   ----------------------- ---------------- 5.8/9.7 MB 483.3 kB/s eta 0:00:09
   ----------------------- ---------------- 5.8/9.7 MB 483.3 kB/s eta 0:00:09
   ----------------------- ---------------- 5.8/9.7 MB 483.3 kB/s eta 0:00:09
   ------------------------ --------------- 6.0/9.7 MB 482.5 kB/s eta 0:00:08
   ------------------------ --------------- 6.0/9.7 MB 482.5 kB/s eta 0:00:08
   ------------------------ --------------- 6.0/9.7 MB 482.5 kB/s eta 0:00:08
   ------------------------ --------------- 6.0/9.7 MB 482.5 kB/s eta 0:00:08
   ------------------------ --------------- 6.0/9.7 MB 482.5 kB/s eta 0:00:08
   ------------------------ --------------- 6.0/9.7 MB 482.5 kB/s eta 0:00:08
   ------------------------ --------------- 6.0/9.7 MB 482.5 kB/s eta 0:00:08
   ------------------------ --------------- 6.0/9.7 MB 482.5 kB/s eta 0:00:08
   ------------------------ --------------- 6.0/9.7 MB 482.5 kB/s eta 0:00:08
   ------------------------- -------------- 6.3/9.7 MB 435.5 kB/s eta 0:00:08
   ------------------------- -------------- 6.3/9.7 MB 435.5 kB/s eta 0:00:08
   ------------------------- -------------- 6.3/9.7 MB 435.5 kB/s eta 0:00:08
   ------------------------- -------------- 6.3/9.7 MB 435.5 kB/s eta 0:00:08
   ------------------------- -------------- 6.3/9.7 MB 435.5 kB/s eta 0:00:08
   -------------------------- ------------- 6.6/9.7 MB 422.1 kB/s eta 0:00:08
   -------------------------- ------------- 6.6/9.7 MB 422.1 kB/s eta 0:00:08
   -------------------------- ------------- 6.6/9.7 MB 422.1 kB/s eta 0:00:08
   -------------------------- ------------- 6.6/9.7 MB 422.1 kB/s eta 0:00:08
   --------------------------- ------------ 6.8/9.7 MB 414.5 kB/s eta 0:00:08
   --------------------------- ------------ 6.8/9.7 MB 414.5 kB/s eta 0:00:08
   --------------------------- ------------ 6.8/9.7 MB 414.5 kB/s eta 0:00:08
   --------------------------- ------------ 6.8/9.7 MB 414.5 kB/s eta 0:00:08
   --------------------------- ------------ 6.8/9.7 MB 414.5 kB/s eta 0:00:08
   --------------------------- ------------ 6.8/9.7 MB 414.5 kB/s eta 0:00:08
   ----------------------------- ---------- 7.1/9.7 MB 403.9 kB/s eta 0:00:07
   ----------------------------- ---------- 7.1/9.7 MB 403.9 kB/s eta 0:00:07
   ----------------------------- ---------- 7.1/9.7 MB 403.9 kB/s eta 0:00:07
   ----------------------------- ---------- 7.1/9.7 MB 403.9 kB/s eta 0:00:07
   ------------------------------ --------- 7.3/9.7 MB 399.8 kB/s eta 0:00:07
   ------------------------------ --------- 7.3/9.7 MB 399.8 kB/s eta 0:00:07
   ------------------------------ --------- 7.3/9.7 MB 399.8 kB/s eta 0:00:07
   ------------------------------ --------- 7.3/9.7 MB 399.8 kB/s eta 0:00:07
   ------------------------------ --------- 7.3/9.7 MB 399.8 kB/s eta 0:00:07
   ------------------------------- -------- 7.6/9.7 MB 389.5 kB/s eta 0:00:06
   ------------------------------- -------- 7.6/9.7 MB 389.5 kB/s eta 0:00:06
   ------------------------------- -------- 7.6/9.7 MB 389.5 kB/s eta 0:00:06
   -------------------------------- ------- 7.9/9.7 MB 389.6 kB/s eta 0:00:05
   -------------------------------- ------- 7.9/9.7 MB 389.6 kB/s eta 0:00:05
   -------------------------------- ------- 7.9/9.7 MB 389.6 kB/s eta 0:00:05
   -------------------------------- ------- 7.9/9.7 MB 389.6 kB/s eta 0:00:05
   --------------------------------- ------ 8.1/9.7 MB 388.4 kB/s eta 0:00:05
   --------------------------------- ------ 8.1/9.7 MB 388.4 kB/s eta 0:00:05
   --------------------------------- ------ 8.1/9.7 MB 388.4 kB/s eta 0:00:05
   --------------------------------- ------ 8.1/9.7 MB 388.4 kB/s eta 0:00:05
   ---------------------------------- ----- 8.4/9.7 MB 387.0 kB/s eta 0:00:04
   ---------------------------------- ----- 8.4/9.7 MB 387.0 kB/s eta 0:00:04
   ---------------------------------- ----- 8.4/9.7 MB 387.0 kB/s eta 0:00:04
   ---------------------------------- ----- 8.4/9.7 MB 387.0 kB/s eta 0:00:04
   ---------------------------------- ----- 8.4/9.7 MB 387.0 kB/s eta 0:00:04
   ----------------------------------- ---- 8.7/9.7 MB 380.5 kB/s eta 0:00:03
   ----------------------------------- ---- 8.7/9.7 MB 380.5 kB/s eta 0:00:03
   ----------------------------------- ---- 8.7/9.7 MB 380.5 kB/s eta 0:00:03
   ----------------------------------- ---- 8.7/9.7 MB 380.5 kB/s eta 0:00:03
   ----------------------------------- ---- 8.7/9.7 MB 380.5 kB/s eta 0:00:03
   ----------------------------------- ---- 8.7/9.7 MB 380.5 kB/s eta 0:00:03
   ------------------------------------ --- 8.9/9.7 MB 369.8 kB/s eta 0:00:03
   ------------------------------------ --- 8.9/9.7 MB 369.8 kB/s eta 0:00:03
   ------------------------------------ --- 8.9/9.7 MB 369.8 kB/s eta 0:00:03
   ------------------------------------ --- 8.9/9.7 MB 369.8 kB/s eta 0:00:03
   ------------------------------------- -- 9.2/9.7 MB 368.5 kB/s eta 0:00:02
   ------------------------------------- -- 9.2/9.7 MB 368.5 kB/s eta 0:00:02
   ------------------------------------- -- 9.2/9.7 MB 368.5 kB/s eta 0:00:02
   ------------------------------------- -- 9.2/9.7 MB 368.5 kB/s eta 0:00:02
   ------------------------------------- -- 9.2/9.7 MB 368.5 kB/s eta 0:00:02
   ------------------------------------- -- 9.2/9.7 MB 368.5 kB/s eta 0:00:02
   ------------------------------------- -- 9.2/9.7 MB 368.5 kB/s eta 0:00:02
   ------------------------------------- -- 9.2/9.7 MB 368.5 kB/s eta 0:00:02
   ------------------------------------- -- 9.2/9.7 MB 368.5 kB/s eta 0:00:02
   -------------------------------------- - 9.4/9.7 MB 354.4 kB/s eta 0:00:01
   -------------------------------------- - 9.4/9.7 MB 354.4 kB/s eta 0:00:01
   -------------------------------------- - 9.4/9.7 MB 354.4 kB/s eta 0:00:01
   ---------------------------------------- 9.7/9.7 MB 357.5 kB/s eta 0:00:00
Downloading tzdata-2025.3-py2.py3-none-any.whl (348 kB)
Installing collected packages: tzdata, pandas
Successfully installed pandas-3.0.1 tzdata-2025.3

[notice] A new release of pip is available: 25.0.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [30]:
!pip list

Package                 Version
----------------------- -----------
asttokens               3.0.1
colorama                0.4.6
comm                    0.2.3
debugpy                 1.8.20
decorator               5.2.1
executing               2.2.1
ipykernel               7.2.0
ipython                 9.12.0
ipython_pygments_lexers 1.1.1
jedi                    0.19.2
jupyter_client          8.8.0
jupyter_core            5.9.1
matplotlib-inline       0.2.1
nest-asyncio            1.6.0
numpy                   2.4.4
packaging               26.0
pandas                  3.0.1
parso                   0.8.6
pip                     25.0.1
platformdirs            4.9.4
prompt_toolkit          3.0.52
psutil                  7.2.2
pure_eval               0.2.3
Pygments                2.20.0
python-dateutil         2.9.0.post0
pyzmq                   27.1.0
six                     1.17.0
stack-data              0.6.3
tornado                 6.5.5
traitlets               5.14.3
tzdata                  2025.3
wcwidth                 0.6.0

##판다스 기초

-핵심구조
    -DataFrame(데이터프레임) : 기준. 2차원 배열
    -Series(시리즈) 최소원소,1차원 배열

    표만들때 사용하는 것

In [31]:
# 판다스 라이브러리 로드
import pandas as pd

In [35]:
# 시리즈
s1=pd.Series ([10,20,30])
s1

0    10
1    20
2    30
dtype: int64

In [36]:
[10,20,30]

[10, 20, 30]

In [37]:
# 데이터프레임
data ={
    'name':['유고','요미','철수'],
    'score':[90,100,36]
}
data

{'name': ['유고', '요미', '철수'], 'score': [90, 100, 36]}

In [39]:
df = pd.DataFrame(data)
df

  name  score
0   유고     90
1   요미    100
2   철수     36

In [44]:
# CSV 읽기
df = pd.read_csv('./도서정보.csv',encoding = 'utf-8')
df

,번호,서명,저자,발행자,발행년,청구기호,자료실
0,1,해럴드와 마법 크레용 [비디오녹화자료],카를로스 살다냐 감독,소니 픽쳐스 홈엔터테인먼트 [공급],2025,DVD 688.2-2246,[해운대인문학]디지털자료실
1,2,나처럼 예쁜 여자 [비디오녹화자료],프랑수아 트뤼포 감독,Art Film [수입·제조],2024,DVD 688.2-2247,[해운대인문학]디지털자료실
2,3,조커 [비디오녹화자료] : 폴리 아 되,토드 필립스 감독,해리슨 앤 컴퍼니 [제조·판매],[2025],DVD 688.2-2248,[해운대인문학]디지털자료실
3,4,"신비아파트 고스트볼 ZERO [비디오녹화자료]. 2, 싹트는 울음소리, 뿌리 괴수의 진실",박홍근 총감독,뮤라인 [제작·판매],2025,DVD 688.6-1141-2,[해운대인문학]디지털자료실
4,5,마당을 나온 암탉 [비디오녹화자료],오성윤 감독,미디어포유 [제작·판매],2025,DVD 688.6-335=2,[해운대인문학]디지털자료실
5,6,더 파일럿 [비디오녹화자료] : 드론 어택,폴 듀세 감독,미디어포유 [제작·판매],2025,DVD 688.2-2249,[해운대인문학]디지털자료실
6,7,새터데이 나이트 [비디오녹화자료],제이슨 라이트먼 감독,소니 픽쳐스 홈엔터테인먼트 [공급],2025,DVD 688.2-2250,[해운대인문학]디지털자료실
7,8,구룡성채 [비디오녹화자료] : 무법지대,정바오루이 감독,플레인아카이브 [DVD 제작·판매],[2025],DVD 688.2-2251,[해운대인문학]디지털자료실
8,9,"신비아파트 고스트볼 ZERO [비디오녹화자료]. 3, 수상한 공사장의 비밀",박홍근 총감독,뮤라인 [제작·판매],2025,DVD 688.6-1141-3,[해운대인문학]디지털자료실
9,10,베리 미 트와이스 [비디오녹화자료],스티븐 라모트 감독,미디어포유 [제작],2025,DVD 688.2-2252,[해운대인문학]디지털자료실

In [43]:
# 엑셀파일 읽기
df = pd.read_excel('./sample.xlsx')
df

    이름   국어   영어   수학
0  홍길동   95   98   93
1  애슐리  100  100  100

- 엑셀을 읽으려면 openpyxl 모듈이 추가로 필요

```bash
!pip install openpyxl
```

In [42]:
!pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl
Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5

[notice] A new release of pip is available: 25.0.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [45]:
# 데이터 확인 - 기본 상위 5개만 출력
df.head

<bound method NDFrame.head of    번호                                                 서명           저자  \
0   1                              해럴드와 마법 크레용 [비디오녹화자료]  카를로스 살다냐 감독
1   2                                나처럼 예쁜 여자 [비디오녹화자료]  프랑수아 트뤼포 감독
2   3                              조커 [비디오녹화자료] : 폴리 아 되    토드 필립스 감독
3   4  신비아파트 고스트볼 ZERO [비디오녹화자료]. 2, 싹트는 울음소리, 뿌리 괴수의 진실      박홍근 총감독
4   5                                마당을 나온 암탉 [비디오녹화자료]       오성윤 감독
5   6                            더 파일럿 [비디오녹화자료] : 드론 어택      폴 듀세 감독
6   7                                 새터데이 나이트 [비디오녹화자료]  제이슨 라이트먼 감독
7   8                              구룡성채 [비디오녹화자료] : 무법지대     정바오루이 감독
8   9          신비아파트 고스트볼 ZERO [비디오녹화자료]. 3, 수상한 공사장의 비밀      박홍근 총감독
9  10                                베리 미 트와이스 [비디오녹화자료]   스티븐 라모트 감독

                   발행자     발행년              청구기호             자료실
0  소니 픽쳐스 홈엔터테인먼트 [공급]    2025    DVD 688.2-2246  [해운대인문학]디지털자료실
1     Art Film [수입·제조]    2024    DVD 688.2-2247  [해운대인문학]디지털자료실
2    해리슨 앤 컴퍼니 [제조·판매]  [2025]    DVD 688.2-2248  [해운대인문학]디지털자료실
3          뮤라인 [제작·판매]    2025  DVD 688.6-1141-2  [해운대인문학]디지털자료실
4        미디어포유 [제작·판매]    2025   DVD 688.6-335=2  [해운대인문학]디지털자료실
5        미디어포유 [제작·판매]    2025    DVD 688.2-2249  [해운대인문학]디지털자료실
6  소니 픽쳐스 홈엔터테인먼트 [공급]    2025    DVD 688.2-2250  [해운대인문학]디지털자료실
7  플레인아카이브 [DVD 제작·판매]  [2025]    DVD 688.2-2251  [해운대인문학]디지털자료실
8          뮤라인 [제작·판매]    2025  DVD 688.6-1141-3  [해운대인문학]디지털자료실
9           미디어포유 [제작]    2025    DVD 688.2-2252  [해운대인문학]디지털자료실  >

In [46]:
df.head(3)

,번호,서명,저자,발행자,발행년,청구기호,자료실
0,1,해럴드와 마법 크레용 [비디오녹화자료],카를로스 살다냐 감독,소니 픽쳐스 홈엔터테인먼트 [공급],2025,DVD 688.2-2246,[해운대인문학]디지털자료실
1,2,나처럼 예쁜 여자 [비디오녹화자료],프랑수아 트뤼포 감독,Art Film [수입·제조],2024,DVD 688.2-2247,[해운대인문학]디지털자료실
2,3,조커 [비디오녹화자료] : 폴리 아 되,토드 필립스 감독,해리슨 앤 컴퍼니 [제조·판매],[2025],DVD 688.2-2248,[해운대인문학]디지털자료실

In [47]:
df.tail(2)

,번호,서명,저자,발행자,발행년,청구기호,자료실
8,9,"신비아파트 고스트볼 ZERO [비디오녹화자료]. 3, 수상한 공사장의 비밀",박홍근 총감독,뮤라인 [제작·판매],2025,DVD 688.6-1141-3,[해운대인문학]디지털자료실
9,10,베리 미 트와이스 [비디오녹화자료],스티븐 라모트 감독,미디어포유 [제작],2025,DVD 688.2-2252,[해운대인문학]디지털자료실

- Null 값은 통계에서 치명적인 데이터
- Null 데이터가 없도록 만들어주는 것이  데이터분석 핵심작업

In [49]:
# 기초 통계 기본데이터 추출. 컬럼 중 숫자형만 추출가능
df.describe()

             번호
count  10.00000
mean    5.50000
std     3.02765
min     1.00000
25%     3.25000
50%     5.50000
75%     7.75000
max    10.00000

In [50]:
# 컬럼 선택
df['서명']

0                                해럴드와 마법 크레용 [비디오녹화자료]
1                                  나처럼 예쁜 여자 [비디오녹화자료]
2                                조커 [비디오녹화자료] : 폴리 아 되
3    신비아파트 고스트볼 ZERO [비디오녹화자료]. 2, 싹트는 울음소리, 뿌리 괴수의 진실
4                                  마당을 나온 암탉 [비디오녹화자료]
5                              더 파일럿 [비디오녹화자료] : 드론 어택
6                                   새터데이 나이트 [비디오녹화자료]
7                                구룡성채 [비디오녹화자료] : 무법지대
8            신비아파트 고스트볼 ZERO [비디오녹화자료]. 3, 수상한 공사장의 비밀
9                                  베리 미 트와이스 [비디오녹화자료]
Name: 서명, dtype: str

In [51]:
df['서명'].info()

<class 'pandas.Series'>
RangeIndex: 10 entries, 0 to 9
Series name: 서명
Non-Null Count  Dtype
--------------  -----
10 non-null     str
dtypes: str(1)
memory usage: 212.0 bytes

In [52]:
# 새로 데이터프레임 읽기
df = pd.read_excel('./sample.xlsx')
df

    이름   국어     영어   수학
0  홍길동   95   98.0   93
1  애슐리  100  100.0  100
2  성명건   90    NaN   78
3  김예성   50   50.0  100

In [53]:
# 국어점수가 60점 이상만 필터링
df['국어']>60

0     True
1     True
2     True
3    False
Name: 국어, dtype: bool

In [54]:
#60점 초과인 학생만 추출
df[df['국어']>60]

    이름   국어     영어   수학
0  홍길동   95   98.0   93
1  애슐리  100  100.0  100
2  성명건   90    NaN   78

In [ ]:
#영어점수가 50점이상 필터링
df['영어']>=50

0     True
1     True
2    False
3    False
Name: 영어, dtype: bool

In [56]:
df[df['영어']>=50]

    이름   국어     영어   수학
0  홍길동   95   98.0   93
1  애슐리  100  100.0  100
3  김예성   50   50.0  100

In [57]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   이름      4 non-null      str
 1   국어      4 non-null      int64
 2   영어      3 non-null      float64
 3   수학      4 non-null      int64
dtypes: float64(1), int64(2), str(1)
memory usage: 260.0 bytes

In [58]:
df.describe()

               국어          영어          수학
count    4.000000    3.000000    4.000000
mean    83.750000   82.666667   92.750000
std     22.867371   28.307832   10.372239
min     50.000000   50.000000   78.000000
25%     80.000000   74.000000   89.250000
50%     92.500000   98.000000   96.500000
75%     96.250000   99.000000  100.000000
max    100.000000  100.000000  100.000000

#### 결측치
-들어 있어야하는 곳에 들어있지 않은 값

In [ ]:
## 새 컬럼 만들기
dfb['수학_1']=df['수학']-5

In [62]:
df

    이름   국어     영어   수학  수학_1
0  홍길동   95   98.0   93    88
1  애슐리  100  100.0  100    95
2  성명건   90    NaN   78    73
3  김예성   50   50.0  100    95

In [63]:
# w정렬

df.sort_values('수학_1')

    이름   국어     영어   수학  수학_1
2  성명건   90    NaN   78    73
0  홍길동   95   98.0   93    88
1  애슐리  100  100.0  100    95
3  김예성   50   50.0  100    95

In [64]:
df.sort_values('수학_1',ascending=False)

    이름   국어     영어   수학  수학_1
1  애슐리  100  100.0  100    95
3  김예성   50   50.0  100    95
0  홍길동   95   98.0   93    88
2  성명건   90    NaN   78    73

In [ ]:
#결측치 처리 - 결측치가 있는 데이터 삭제
df1 =df.dropna()
df1

    이름   국어     영어   수학  수학_1
0  홍길동   95   98.0   93    88
1  애슐리  100  100.0  100    95
3  김예성   50   50.0  100    95

In [ ]:
# 결측치가 있는 값은 모두 같은 값으로 대체
df2 = df.fillna(45)
df2

    이름   국어     영어   수학  수학_1
0  홍길동   95   98.0   93    88
1  애슐리  100  100.0  100    95
2  성명건   90   45.0   78    73
3  김예성   50   50.0  100    95

In [67]:
# 그룹화 (GroubBy)
df.groupby('수학').count()

     이름  국어  영어  수학_1
수학
78    1   1   0     1
93    1   1   1     1
100   2   2   2     2

In [68]:
df[['국어','영어','수학']].fillna(45).grouby('수학').mean()

AttributeError: 'DataFrame' object has no attribute 'grouby'

In [69]:
df.to_csv(',/scores.csv',encoding ='utf-8')

OSError: Cannot save file into a non-existent directory: ','